import * as T from 'three';import {flameMaterial} from '../rendering/Flame';import {woodMaterial,stoneMaterial} from '../rendering/materials';import {STATIONS,type Station,stationStatus} from './stations';import type {CollisionBox} from '../physics/PhysicsWorld';
export class StationRenderer {
 readonly objects=new Map<string,T.Group>();readonly group=new T.Group();readonly ghost=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshBasicMaterial({color:0x8cb397,transparent:true,opacity:.35,depthWrite:false}));
 private interaction=new T.MeshBasicMaterial({visible:false});
 private wood=woodMaterial('#716451');private stone=stoneMaterial();private iron=new T.MeshStandardMaterial({color:0x545b59,roughness:.8,metalness:.35});private cloth=new T.MeshStandardMaterial({color:0x626b52,roughness:1});private fire=flameMaterial();private lights=[new T.PointLight(0xffc394,0,10,2),new T.PointLight(0xffc394,0,10,2)];
 constructor(scene:T.Scene){scene.add(this.group,this.ghost,...this.lights);this.ghost.visible=false;}
 private box(g:T.Object3D,x:number,y:number,z:number,w:number,h:number,d:number,m:T.Material){const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;g.add(mesh);return mesh;}
 private make(s:Station){const g=new T.Group(),[w,h,d]=STATIONS[s.kind].size;
 if(s.kind==='storage'||s.kind==='loot'){for(let i=0;i<6;i++){this.box(g,-w/2+w*(i+.5)/6,h/2,0,w/6-.018,h,d,this.wood);}for(const x of [-w*.36,w*.36]){this.box(g,x,h+.015,0,.08,.04,d+.03,this.iron);for(const z of [-d/2,d/2])this.box(g,x,h/2,z,.07,h,.025,this.iron);}this.box(g,0,h*.7,d/2+.02,.15,.13,.04,this.iron);}
 else if(s.kind.startsWith('workbench')){for(const x of [-.72,.72])for(const z of [-.28,.28])this.box(g,x,.43,z,.11,.86,.11,this.wood);this.box(g,0,.92,0,w,.16,d,this.wood);this.box(g,0,.2,0,w-.15,.08,d-.1,this.wood);this.box(g,-.48,1.12,0,.25,.25,.24,this.iron);const level=Number(s.kind.slice(-1));for(let i=0;i<level;i++)this.box(g,.1+i*.22,1.05,0,.12,.13,.5,this.iron);if(level>1){this.box(g,0,1.48,-.35,1.6,.7,.06,this.wood);for(let i=0;i<5;i++)this.box(g,-.6+i*.3,1.5,-.3,.05,.35,.035,this.iron);}}
 else if(s.kind==='bedroll'){this.box(g,0,.08,0,.85,.16,1.9,this.cloth);const roll=new T.Mesh(new T.CylinderGeometry(.17,.17,.78,12),this.cloth);roll.rotation.z=Math.PI/2;roll.position.set(0,.23,-.68);g.add(roll);for(const x of [-.29,.29])this.box(g,x,.17,0,.035,.025,1.9,this.wood);}
 else {if(s.kind==='furnace'){const shell=new T.Mesh(new T.CylinderGeometry(.43,.56,1.3,10,1,true),this.stone);shell.position.y=.65;g.add(shell);this.box(g,0,1.4,0,.34,.4,.34,this.iron);this.box(g,0,.37,.53,.52,.5,.04,this.iron);}else for(let i=0;i<9;i++){const stone=new T.Mesh(new T.DodecahedronGeometry(.16),this.stone);stone.position.set(Math.cos(i*7)*.45,.11,Math.sin(i*7)*.45);g.add(stone);}for(let i=0;i<3;i++){const log=this.box(g,0,.13,0,.13,.13,.7,this.wood);log.rotation.y=i*Math.PI/3;}for(let i=0;i<3;i++){const f=new T.Mesh(new T.PlaneGeometry(.32,.65),this.fire);f.position.set((i-1)*.09,.47,s.kind==='furnace'?.56:0);f.rotation.y=i*Math.PI/3;f.name='flame';g.add(f);}}
 this.box(g,0,h/2,0,w,h,d,this.interaction);
 g.position.set(s.position.x,s.position.y,s.position.z);g.rotation.y=s.rotation;g.traverse(o=>o.userData.stationId=s.id);return g;}
 sync(stations:Station[]){const ids=new Set(stations.map(s=>s.id));for(const [id,o]of this.objects)if(!ids.has(id)){this.disposeObject(o);this.objects.delete(id);}for(const s of stations)if(!this.objects.has(s.id)){const g=this.make(s);this.objects.set(s.id,g);this.group.add(g);}}
 update(stations:Station[],time:number,p:T.Vector3){this.fire.uniforms.time.value=time;let lit=0;for(const s of stations){const active=stationStatus(s)==='PROCESSING',g=this.objects.get(s.id);g?.traverse(o=>{if(o.name==='flame'){o.visible=active;o.scale.set(1+.12*Math.sin(time*8+o.id),.8+.24*Math.sin(time*5+o.id),1);o.rotation.y=time*.3+o.id;}});if(active&&lit<2&&p.distanceTo(new T.Vector3(s.position.x,s.position.y,s.position.z))<18){const l=this.lights[lit++];l.position.set(s.position.x,s.position.y+.65,s.position.z);l.intensity=5+Math.sin(time*4)*.4;}}for(let i=lit;i<2;i++)this.lights[i].intensity=0;}
 boxes(s:Station):CollisionBox[]{const [w,h,d]=STATIONS[s.kind].size;return [{position:{x:s.position.x,y:s.position.y+h/2,z:s.position.z},halfExtents:{x:w/2,y:h/2,z:d/2},rotation:s.rotation}];}
 preview(kind:Station['kind']|null,p?:T.Vector3,rotation=0,valid=true){this.ghost.visible=!!kind&&!!p;if(kind&&p){const [w,h,d]=STATIONS[kind].size;this.ghost.scale.set(w,h,d);this.ghost.position.copy(p);this.ghost.position.y+=h/2;this.ghost.rotation.y=rotation;this.ghost.material.color.set(valid?0x8cb397:0xcd685a);}}
 private disposeObject(o:T.Object3D){o.traverse(x=>{if(x instanceof T.Mesh)x.geometry.dispose();});o.removeFromParent();}
 dispose(){this.disposeObject(this.group);this.disposeObject(this.ghost);this.lights.forEach(l=>l.removeFromParent());[this.wood,this.stone,this.iron,this.cloth,this.fire,this.ghost.material,this.interaction].forEach(m=>m.dispose());}
}
