import type {CollisionBox} from '../physics/PhysicsWorld';
import * as T from 'three';import type {Environment} from '../rendering/environment';import type {GameState,Vec3} from '../core/types';import {ensureProgression} from './progression';import {createStation,type Station} from './stations';import {insertItem} from '../inventory/inventory';import {woodMaterial} from '../rendering/materials';
export interface Landmark {id:string;name:string;position:Vec3;kind:number}
const NAMES=['Coastal utility shack','Old relay tower','Quarry outpost','Overgrown camp'];
const LOOT=[{item:'ore' as const,min:20,max:55},{item:'metal' as const,min:4,max:12},{item:'fiber' as const,min:15,max:35},{item:'berries' as const,min:3,max:8}];
export class WorldSurvival {
 readonly pois:Landmark[]=[];readonly group=new T.Group();readonly trails:Vec3[][]=[];private wood=woodMaterial('#696858');private metal=new T.MeshStandardMaterial({color:0x64706b,roughness:.88,metalness:.3});private cloth=new T.MeshStandardMaterial({color:0x6b755d,roughness:1,side:T.DoubleSide});private trail=new T.MeshStandardMaterial({color:0x706b55,roughness:1,transparent:true,opacity:.45,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1});
 constructor(private env:Environment,scene:T.Scene,private seed:number){scene.add(this.group);for(let k=0;k<4;k++){let best:Vec3|null=null,score=Infinity;const angle=k*Math.PI/2+.5;for(let i=0;i<1800;i++){const a=angle+Math.sin(i*2.31+seed)*.65,r=85+(i%160);const x=Math.cos(a)*r,z=Math.sin(a)*r,y=env.heightAt(x,z);if(y<3||y>36)continue;const slope=env.terrain.slopeAt(x,z);if(slope>.36)continue;if(this.pois.some(p=>Math.hypot(p.position.x-x,p.position.z-z)<65))continue;const nearby=env.colliders.some(c=>Math.abs(c.position.x-x)<5+c.halfExtents.x&&Math.abs(c.position.z-z)<5+c.halfExtents.z);if(nearby)continue;const rank=slope+Math.abs(r-175)*.001;if(rank<score){score=rank;best={x,y,z};}}if(!best)continue;const poi={id:`poi-${k}`,name:NAMES[k],position:best,kind:k};this.pois.push(poi);this.make(poi);}
 let from=env.spawn;for(const poi of this.pois){const points:Vec3[]=[];const distance=Math.hypot(poi.position.x-from.x,poi.position.z-from.z),segments=Math.ceil(distance/2);for(let i=0;i<=segments;i++){const t=i/segments,x=T.MathUtils.lerp(from.x,poi.position.x,t)+Math.sin(t*Math.PI)*Math.sin(seed+i*.03)*5,z=T.MathUtils.lerp(from.z,poi.position.z,t);points.push({x,y:env.heightAt(x,z)+.03,z});}this.trails.push(points);const verts:number[]=[];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];if(a.y<.3||b.y<.3)continue;const dx=b.x-a.x,dz=b.z-a.z,l=Math.hypot(dx,dz),nx=dz/l*.75,nz=-dx/l*.75;const quad=[[a.x+nx,a.z+nz],[a.x-nx,a.z-nz],[b.x+nx,b.z+nz],[b.x-nx,b.z-nz]];for(const j of [0,1,2,2,1,3]){const [x,z]=quad[j];verts.push(x,env.heightAt(x,z)+.035,z);}}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(verts,3));geo.computeVertexNormals();const mesh=new T.Mesh(geo,this.trail);mesh.receiveShadow=true;this.group.add(mesh);from=poi.position;}}
 private box(g:T.Group,x:number,y:number,z:number,w:number,h:number,d:number,m:T.Material){const mesh=new T.Mesh(new T.BoxGeometry(w,h,d),m);mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;g.add(mesh);return mesh;}
 private make(p:Landmark){const g=new T.Group();g.position.set(p.position.x,p.position.y,p.position.z);this.group.add(g);if(p.kind===1){for(const x of [-1,1])for(const z of [-1,1]){const beam=this.box(g,x,5,z,.12,10,.12,this.metal);beam.rotation.z=-x*.05;}for(let i=1;i<7;i++){this.box(g,0,i*1.4,0,2.2,.1,2.2,this.metal);}const dish=new T.Mesh(new T.CylinderGeometry(1.2,.15,.3,16,1,true),this.metal);dish.rotation.x=Math.PI*.35;dish.position.set(0,8,1);g.add(dish);}else if(p.kind===3){const tent=new T.Mesh(new T.ConeGeometry(1.8,2.3,4,1,true),this.cloth);tent.position.y=1.15;tent.rotation.y=Math.PI/4;g.add(tent);this.box(g,-2,.18,0,.3,.3,2,this.wood);}else{for(const x of [-2,2])for(const z of [-1.6,1.6])this.box(g,x,1.4,z,.18,2.8,.18,this.wood);for(let i=0;i<12;i++){this.box(g,-2+i*.35,1.2,-1.6,.32,2.4,.12,this.wood);}this.box(g,0,2.8,0,4.5,.13,3.8,this.metal).rotation.z=.08;if(p.kind===2){for(let i=0;i<3;i++)this.box(g,3,.35,i*.7,1,.7,.5,this.metal);}}}
 populate(state:GameState){const p=ensureProgression(state);if(p.lootGenerated)return;for(const poi of this.pois){const pos={x:poi.position.x+2.7,y:this.env.heightAt(poi.position.x+2.7,poi.position.z+2.4),z:poi.position.z+2.4};const s=createStation(`loot-${poi.id}`,'loot',pos);for(let i=0;i<LOOT.length;i++){const l=LOOT[i],rand=Math.abs(Math.sin(this.seed*13.31+poi.kind*71+i*9.7));insertItem(s.inventory,l.item,l.min+Math.floor(rand*(l.max-l.min)));}p.stations.push(s);}p.lootGenerated=true;}
 collisionBoxes():CollisionBox[]{const result:CollisionBox[]=[];for(const p of this.pois){if(p.kind===1){for(const x of [-1,1])for(const z of [-1,1])result.push({position:{x:p.position.x+x,y:p.position.y+5,z:p.position.z+z},halfExtents:{x:.15,y:5,z:.15}});}else if(p.kind!==3){result.push({position:{x:p.position.x,y:p.position.y+1.2,z:p.position.z-1.6},halfExtents:{x:2.2,y:1.2,z:.12}});}}return result;}
 dispose(){this.group.traverse(o=>{if(o instanceof T.Mesh)o.geometry.dispose();});this.group.removeFromParent();[this.wood,this.metal,this.cloth,this.trail].forEach(m=>m.dispose());}
}
export class IslandMap {
 readonly root=document.createElement('section');private canvas=document.createElement('canvas');private base=document.createElement('canvas');private ctx:CanvasRenderingContext2D;
 constructor(parent:HTMLElement,world:WorldSurvival,env:Environment,private onWaypoint:(p:{x:number;z:number}|null)=>void,close:()=>void){this.root.className='survival-panel world-map';this.root.hidden=true;this.root.innerHTML='<header><span>TIDELAND / ISLAND SURVEY</span><button>CLOSE · M / ESC</button></header><p>Click to set waypoint · Right-click to clear · North is up</p>';this.root.querySelector('button')!.onclick=close;this.canvas.width=this.canvas.height=this.base.width=this.base.height=720;this.ctx=this.canvas.getContext('2d')!;this.root.append(this.canvas);parent.append(this.root);const c=this.base.getContext('2d')!,data=c.createImageData(720,720);for(let z=0;z<720;z++)for(let x=0;x<720;x++){const h=env.heightAt(x-360,z-360),i=(z*720+x)*4,col=h<0?[39,66,75]:h<2?[154,147,117]:[72+h*1.2,88+h*.9,64+h*.9];data.data.set([...col,255],i);}c.putImageData(data,0,0);c.strokeStyle='#c0ad80';c.lineWidth=2;for(const trail of world.trails){c.beginPath();trail.forEach((p,i)=>i?c.lineTo(p.x+360,p.z+360):c.moveTo(p.x+360,p.z+360));c.stroke();}c.font='13px sans-serif';for(const p of world.pois){c.fillStyle='#e4d4a6';c.fillRect(p.position.x+355,p.position.z+355,10,10);c.fillText(p.name,p.position.x+368,p.position.z+360);}this.canvas.onclick=e=>{const r=this.canvas.getBoundingClientRect();this.onWaypoint({x:(e.clientX-r.left)/r.width*720-360,z:(e.clientY-r.top)/r.height*720-360});};this.canvas.oncontextmenu=e=>{e.preventDefault();this.onWaypoint(null);};}
 get isOpen(){return !this.root.hidden;}show(){this.root.hidden=false;}close(){this.root.hidden=true;}update(p:Vec3,yaw:number,waypoint?:{x:number;z:number}){if(!this.isOpen)return;const c=this.ctx;c.drawImage(this.base,0,0);if(waypoint){c.strokeStyle='#e3a877';c.lineWidth=3;c.strokeRect(waypoint.x+352,waypoint.z+352,16,16);}c.save();c.translate(p.x+360,p.z+360);c.rotate(-yaw);c.fillStyle='#f0f4e4';c.beginPath();c.moveTo(0,-10);c.lineTo(-6,7);c.lineTo(6,7);c.closePath();c.fill();c.restore();}dispose(){this.root.remove();}}
