from pathlib import Path

ROOT=Path('Projekty/Tideland')

def read(path): return (ROOT/path).read_text()
def write(path,text): (ROOT/path).write_text(text)
def replace_once(text,old,new,label):
    if old not in text: raise SystemExit(f'{label}: source text not found')
    return text.replace(old,new,1)

# 1) Buffered, DPI-normalized mouse look with spike protection.
write('src/input/MouseLookFilter.ts', '''export interface LookDelta {x:number;y:number}\n\n/**\n * Coalesces high-frequency pointer-lock mouse events into one render-frame delta.\n * This prevents browser stalls from replaying a burst of movement as a camera jump.\n */\nexport class MouseLookFilter {\n  private x=0;\n  private y=0;\n  constructor(private readonly maxPerFrame=180){}\n  add(dx:number,dy:number,devicePixelRatio=1){\n    if(!Number.isFinite(dx)||!Number.isFinite(dy))return;\n    const dpr=Number.isFinite(devicePixelRatio)?Math.max(1,devicePixelRatio):1;\n    this.x+=dx/dpr;\n    this.y+=dy/dpr;\n  }\n  consume():LookDelta{\n    let x=this.x,y=this.y;this.x=0;this.y=0;\n    const length=Math.hypot(x,y);\n    if(length>this.maxPerFrame&&length>0){const scale=this.maxPerFrame/length;x*=scale;y*=scale;}\n    return {x,y};\n  }\n  clear(){this.x=0;this.y=0;}\n}\n''')

write('src/input/Input.ts', '''import {MouseLookFilter} from './MouseLookFilter';\n\nexport class Input {\n  readonly keys = new Set<string>();\n  locked = false;\n  onLook: (x:number,y:number)=>void = ()=>{};\n  onKey: (code:string)=>void = ()=>{};\n  onClick: (button:number)=>void = ()=>{};\n  onLockChange: (locked:boolean)=>void = ()=>{};\n  onWheel:(direction:number)=>void=()=>{};\n  private handlers: Array<()=>void> = [];\n  private readonly lookFilter=new MouseLookFilter(180);\n  private lookFrame=0;\n  private ignoreLookUntil=0;\n  constructor(private canvas:HTMLCanvasElement) {\n    const bind = (target:EventTarget,type:string,fn:EventListener) => {target.addEventListener(type,fn);this.handlers.push(()=>target.removeEventListener(type,fn));};\n    bind(window,'keydown',((e:KeyboardEvent)=>{\n      const target=e.target;\n      if (target instanceof HTMLElement && target.matches('input,select,textarea')) return;\n      if (['Tab','Space','ArrowUp','ArrowDown','F3'].includes(e.code)) e.preventDefault();\n      this.keys.add(e.code); if (!e.repeat) this.onKey(e.code);\n    }) as EventListener);\n    bind(window,'keyup',((e:KeyboardEvent)=>{this.keys.delete(e.code);}) as EventListener);\n    bind(document,'mousemove',((e:MouseEvent)=>{\n      if(!this.locked||performance.now()<this.ignoreLookUntil)return;\n      this.lookFilter.add(e.movementX,e.movementY,window.devicePixelRatio||1);\n      if(!this.lookFrame)this.lookFrame=requestAnimationFrame(()=>this.flushLook());\n    }) as EventListener);\n    bind(document,'pointerlockchange',()=>{\n      this.locked=document.pointerLockElement===canvas;this.keys.clear();this.resetLook();\n      if(this.locked)this.ignoreLookUntil=performance.now()+80;\n      this.onLockChange(this.locked);\n    });\n    bind(canvas,'mousedown',((e:MouseEvent)=>{e.preventDefault();this.onClick(e.button);}) as EventListener);\n    bind(canvas,'contextmenu',(e)=>e.preventDefault());\n    bind(canvas,'wheel',((e:WheelEvent)=>{e.preventDefault();this.onWheel(Math.sign(e.deltaY));}) as EventListener);\n    bind(window,'blur',()=>{this.keys.clear();this.resetLook();this.release();});\n  }\n  private flushLook(){\n    this.lookFrame=0;\n    const delta=this.lookFilter.consume();\n    if(this.locked&&(delta.x!==0||delta.y!==0))this.onLook(delta.x,delta.y);\n  }\n  private resetLook(){\n    this.lookFilter.clear();\n    if(this.lookFrame){cancelAnimationFrame(this.lookFrame);this.lookFrame=0;}\n  }\n  down(...keys:string[]) {return keys.some(k=>this.keys.has(k));}\n  async lock() {try {await this.canvas.requestPointerLock();}catch { /* Browser may reject while another lock request is leaving. A click retries. */ }}\n  release(){if(document.pointerLockElement)document.exitPointerLock();this.keys.clear();this.resetLook();}\n  dispose(){this.resetLook();this.handlers.forEach(fn=>fn());}\n}\n''')

# 2) Lower and finer camera sensitivity.
p='src/player/PlayerController.ts';s=read(p)
s=replace_once(s,"look(dx:number,dy:number){this.yaw-=dx*0.002*this.settings.sensitivity;const ySign=this.settings.invertY?1:-1;this.pitch=THREE.MathUtils.clamp(this.pitch+dy*0.002*this.settings.sensitivity*ySign,-1.48,1.48);this.camera.rotation.order='YXZ';this.camera.rotation.set(this.pitch,this.yaw,0);}","look(dx:number,dy:number){const scale=0.0009*this.settings.sensitivity;this.yaw-=dx*scale;const ySign=this.settings.invertY?1:-1;this.pitch=THREE.MathUtils.clamp(this.pitch+dy*scale*ySign,-1.48,1.48);this.camera.rotation.order='YXZ';this.camera.rotation.set(this.pitch,this.yaw,0);}",'look sensitivity scale')
write(p,s)

p='src/save/storage.ts';s=read(p)
s=replace_once(s,"sensitivity: finite(value.sensitivity, 0.1, 3) ? value.sensitivity : DEFAULT_SETTINGS.sensitivity,","sensitivity: finite(value.sensitivity, 0.05, 3) ? value.sensitivity : DEFAULT_SETTINGS.sensitivity,",'settings sensitivity range')
write(p,s)

# 3) Real loading progress UI and finer sensitivity slider.
p='src/ui/UI.ts';s=read(p)
s=replace_once(s,"${this.slider('sensitivity','Mouse sensitivity',0.2,3,0.1)}","${this.slider('sensitivity','Mouse sensitivity <small>Buffered and normalized across high-DPI displays</small>',0.05,2.5,0.05)}",'sensitivity slider')
s=replace_once(s,'<div class="loading-screen" hidden><div class="loading-mark">${mark}</div><h2>FINDING YOUR SHORE</h2><div class="loading-bar"></div><p>Shaping the land. Letting the wild in.</p></div>','<div class="loading-screen" hidden><div class="loading-mark">${mark}</div><h2>FINDING YOUR SHORE</h2><div class="loading-bar"><i class="loading-bar-fill"></i></div><div class="loading-meta"><span class="loading-status">Preparing engine</span><b class="loading-percent">0%</b></div><p>Shaping the land. Letting the wild in.</p></div>','loading markup')
s=replace_once(s,"  setLoading(loading: boolean): void { this.find('.loading-screen').hidden = !loading; }","  setLoading(loading: boolean): void { this.find('.loading-screen').hidden = !loading; if(loading)this.setLoadingProgress(0,'Preparing engine'); }\n  setLoadingProgress(progress:number,status:string):void{const value=Math.max(0,Math.min(100,progress));this.find<HTMLElement>('.loading-bar-fill').style.width=`${value}%`;this.find('.loading-percent').textContent=`${Math.round(value)}%`;this.find('.loading-status').textContent=status;}",'loading methods')
s=replace_once(s,"if(name==='renderScale')return `${Math.round(value*100)}%`;return `${value.toFixed(1)}×`;","if(name==='renderScale')return `${Math.round(value*100)}%`;if(name==='sensitivity')return `${value.toFixed(2)}×`;return `${value.toFixed(1)}×`;",'sensitivity display')
write(p,s)

p='src/ui/style.css';s=read(p)
s=replace_once(s,".loading-bar{width:230px;height:2px;background:#b5c69c20;margin-top:22px;overflow:hidden}.loading-bar:after{content:'';display:block;width:70px;height:100%;background:var(--rust-light);animation:loading-run 1.7s ease-in-out infinite}",".loading-bar{width:280px;height:3px;background:#b5c69c20;margin-top:22px;overflow:hidden}.loading-bar-fill{display:block;width:0;height:100%;background:var(--rust-light);transition:width .18s ease-out;box-shadow:0 0 14px #e0835166}.loading-meta{width:280px;margin-top:10px;display:flex;justify-content:space-between;align-items:center;font-family:var(--title-font);font-size:9px;letter-spacing:.12em;color:#8fa184;text-transform:uppercase}.loading-percent{font-size:12px;font-weight:500;color:#d6ddc9}",'loading bar css')
s=s.replace("@keyframes loading-run{0%{transform:translateX(-70px)}100%{transform:translateX(240px)}}","")
write(p,s)

# 4) Loading stages plus renderer warm-up while the overlay remains visible.
p='src/app/GameApp.ts';s=read(p)
s=replace_once(s,"  async init(){await initPhysics();await this.makeWorld(WORLD.SEED);this.activeWorld=false;this.ui.setLoading(false);this.setScreen('menu');this.installDevAPI();this.renderer.setAnimationLoop(t=>this.frame(t));}","  async init(){this.ui.setLoading(true);await this.loadingStage(5,'Starting physics');await initPhysics();await this.loadingStage(12,'Preparing procedural island');await this.makeWorld(WORLD.SEED);await this.warmUpWorld();this.activeWorld=false;this.ui.setLoading(false);this.setScreen('menu');this.installDevAPI();this.renderer.setAnimationLoop(t=>this.frame(t));}",'init loading')
s=replace_once(s,"    this.environment=new Environment(this.scene,seed,saved ? saved.worldGeneration ?? 1 : 2);","    await this.loadingStage(20,'Shaping terrain');\n    this.environment=new Environment(this.scene,seed,saved ? saved.worldGeneration ?? 1 : 2);",'terrain stage')
s=replace_once(s,"    this.environment.syncNodes(this.simulation.state.nodeChanges);","    this.environment.syncNodes(this.simulation.state.nodeChanges);\n    await this.loadingStage(42,'Placing resources');",'resource stage')
s=replace_once(s,"    this.physics=new PhysicsWorld(this.environment.terrainGeometry,this.environment.colliders,this.simulation.state.player.position);","    this.physics=new PhysicsWorld(this.environment.terrainGeometry,this.environment.colliders,this.simulation.state.player.position);\n    await this.loadingStage(56,'Building collision world');",'physics stage')
s=replace_once(s,"    this.worldSurvival=new WorldSurvival(this.environment,this.scene,seed);this.worldSurvival.populate(this.simulation.state);this.physics.setStructure('landmarks',this.worldSurvival.collisionBoxes());this.weather=new Weather(this.scene);","    this.worldSurvival=new WorldSurvival(this.environment,this.scene,seed);this.worldSurvival.populate(this.simulation.state);this.physics.setStructure('landmarks',this.worldSurvival.collisionBoxes());this.weather=new Weather(this.scene);\n    await this.loadingStage(70,'Growing the island');",'survival stage')
s=replace_once(s,"    this.registerNodes();this.createWaterSource();this.syncStructures();this.syncWorldItems();this.syncHeld();this.applySettings(this.settings);this.player.tick(1/60,this.simulation.state,false);this.accumulator=0;this.autoSave=0;this.building=false;this.candidate=null;","    this.registerNodes();this.createWaterSource();this.syncStructures();this.syncWorldItems();this.syncHeld();this.applySettings(this.settings);this.player.tick(1/60,this.simulation.state,false);this.accumulator=0;this.autoSave=0;this.building=false;this.candidate=null;\n    await this.loadingStage(86,'Finalizing world systems');",'final world stage')
s=replace_once(s,"try {await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));await this.makeWorld(Number.isFinite(seed)?Math.trunc(seed):WORLD.SEED,saved);this.activeWorld=true;this.screen='playing';this.ui.setScreen('playing');this.ui.notify(saved?'Welcome back to your island.':'Washed ashore. Everything begins here.');}","try {await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));await this.makeWorld(Number.isFinite(seed)?Math.trunc(seed):WORLD.SEED,saved);await this.warmUpWorld();this.activeWorld=true;this.screen='playing';this.ui.setScreen('playing');this.ui.notify(saved?'Welcome back to your island.':'Washed ashore. Everything begins here.');}",'start warmup')
anchor="  private setScreen(screen:Screen){"
methods="""  private async loadingStage(progress:number,status:string){this.ui.setLoadingProgress(progress,status);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));}\n  private async warmUpWorld(){\n    await this.loadingStage(90,'Compiling shaders');\n    try{this.renderer.compile(this.scene,this.camera);}catch{ /* A normal render below still warms the pipeline. */ }\n    for(let i=0;i<6;i++){this.renderer.render(this.scene,this.camera);this.ui.setLoadingProgress(92+(i+1)*1.25,'Warming renderer');await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));}\n    this.frameMs=16.7;this.fps=60;this.last=performance.now();\n    this.ui.setLoadingProgress(100,'Ready');\n    await new Promise<void>(resolve=>setTimeout(resolve,80));\n  }\n"""
if anchor not in s: raise SystemExit('setScreen anchor missing')
s=s.replace(anchor,methods+anchor,1)
write(p,s)

# 5) Version and changelog.
p='src/config/version.ts';s=read(p)
s=s.replace("GAME_VERSION='0.2.1'","GAME_VERSION='0.2.2'",1).replace("GAME_BUILD='EA-02.1'","GAME_BUILD='EA-02.2'",1)
needle="export const CHANGELOG:ChangeEntry[]=[\n"
entry="""export const CHANGELOG:ChangeEntry[]=[\n  {version:'0.2.2',date:'2026-09-11',title:'Input stability & loading warm-up',changes:[\n    'Added real staged loading progress and renderer warm-up before the world is revealed.',\n    'Mouse look is now coalesced once per render frame instead of applying every browser event immediately.',\n    'Large pointer-lock bursts are capped so a short browser or GPU stall cannot throw the camera sideways.',\n    'Mouse deltas are normalized for high-DPI displays to make Windows and Retina behaviour more consistent.',\n    'Expanded sensitivity down to 0.05x and reduced the base look scale for precise low-sensitivity play.',\n    'Reset FPS timing after warm-up so startup compilation frames do not pollute the live FPS meter.'\n  ]},\n"""
s=replace_once(s,needle,entry,'version changelog entry')
write(p,s)

for file in ['package.json','package-lock.json']:
    p=file;s=read(p);s=s.replace('"version": "0.2.1"','"version": "0.2.2"',2);write(p,s)

p='CHANGELOG.md';s=read(p)
block="""## 0.2.2 — 2026-09-11\n\nInput stability and loading warm-up patch.\n\n- Added a real staged world-loading meter with named phases and percentages.\n- Pre-compiles shaders and renders warm-up frames before gameplay/menu is revealed.\n- Mouse-look events are coalesced once per display frame instead of changing the camera for every browser event.\n- Caps accumulated mouse bursts after stalls to prevent sudden camera jumps.\n- Normalizes pointer movement for high-DPI/Retina displays.\n- Sensitivity now ranges from `0.05×` to `2.50×` with a lower base rotation scale.\n- Resets FPS timing after warm-up so shader compilation no longer appears as sustained low startup FPS.\n\n"""
s=replace_once(s,'# Tideland changelog\n\n','# Tideland changelog\n\n'+block,'markdown changelog')
write(p,s)

# 6) Pure unit coverage for the input filter.
write('tests/mouse-look-filter.test.ts', '''import {describe,expect,it} from 'vitest';\nimport {MouseLookFilter} from '../src/input/MouseLookFilter';\n\ndescribe('MouseLookFilter',()=>{\n  it('normalizes high-DPI pointer deltas',()=>{const f=new MouseLookFilter();f.add(20,-10,2);expect(f.consume()).toEqual({x:10,y:-5});});\n  it('coalesces multiple events and clears after consume',()=>{const f=new MouseLookFilter();f.add(4,3);f.add(6,2);expect(f.consume()).toEqual({x:10,y:5});expect(f.consume()).toEqual({x:0,y:0});});\n  it('caps a stalled event burst while preserving direction',()=>{const f=new MouseLookFilter(180);f.add(3000,4000);const d=f.consume();expect(Math.hypot(d.x,d.y)).toBeCloseTo(180,6);expect(d.x/d.y).toBeCloseTo(3/4,6);});\n  it('ignores non-finite browser deltas',()=>{const f=new MouseLookFilter();f.add(Number.NaN,4);expect(f.consume()).toEqual({x:0,y:0});});\n});\n''')
print('v0.2.2 patch applied')
